allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: true
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
kind: SecurityContextConstraints
metadata:
  creationTimestamp: "2020-12-22T17:37:40Z"
  generation: 2
  managedFields:
  - apiVersion: security.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:allowHostDirVolumePlugin: {}
      f:allowPrivilegedContainer: {}
      f:fsGroup:
        .: {}
        f:type: {}
      f:groups: {}
      f:runAsUser:
        .: {}
        f:type: {}
      f:seLinuxContext:
        .: {}
        f:type: {}
      f:supplementalGroups:
        .: {}
        f:type: {}
      f:volumes: {}
    manager: kubectl-create
    operation: Update
    time: "2020-12-22T17:37:40Z"
  - apiVersion: security.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:users: {}
    manager: kubectl-edit
    operation: Update
    time: "2020-12-22T17:41:51Z"
  name: waap-scc-priv
  resourceVersion: "341670"
  selfLink: /apis/security.openshift.io/v1/securitycontextconstraints/waap-scc-priv
  uid: 980dfa51-a424-4d0c-8a88-ce593872cc54
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:badwebapp:waap-sa
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
