apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-config
  annotations:
    agentVersion: {{ .Chart.Version }}
  labels:
    app.kubernetes.io/name: nginx-config
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  rules:
  - host: {{.Values.appURL}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.mysvcname}}
            port:
              number: {{.Values.mysvcport}}
